#1.Write a code to reverse a string in python.

In [ ]:
def reverse_string(input_string):
    # Using slicing to reverse the string
    return input_string[::-1]

# Example usage
string = "Hello, World!"
reversed_string = reverse_string(string)
print(f"Original string: {string}")
print(f"Reversed string: {reversed_string}")

Original string: Hello, World!
Reversed string: !dlroW ,olleH

#2.Write a code to count the number of vowels in a string.

In [ ]:
def count_vowels(input_string):
    # Define a set of vowels
    vowels = set("aeiouAEIOU")
    # Initialize a counter
    count = 0

    # Iterate through each character in the input string
    for char in input_string:
        # If the character is a vowel, increment the counter
        if char in vowels:
            count += 1

    return count

# Example usage
string = "Hello, World!"
vowel_count = count_vowels(string)
print(f"The number of vowels in '{string}' is: {vowel_count}")

The number of vowels in 'Hello, World!' is: 3

#3.Write a code to check if a given string is a palindrome or not.

In [ ]:
def is_palindrome(input_string):
    # Convert the string to lowercase and remove non-alphanumeric characters
    cleaned_string = ''.join(char.lower() for char in input_string if char.isalnum())
    # Check if the cleaned string is equal to its reverse
    return cleaned_string == cleaned_string[::-1]

# Example usage
string = "Noon"
if is_palindrome(string):
    print(f"'{string}' is a palindrome.")
else:
    print(f"'{string}' is not a palindrome.")

'Noon' is a palindrome.

#4.Write a code to check if two given strings are anagrams of each other.

In [ ]:
def are_anagrams(string1, string2):
    # Remove spaces, convert to lowercase, and sort the characters of both strings
    cleaned_string1 = sorted(string1.replace(" ", "").lower())
    cleaned_string2 = sorted(string2.replace(" ", "").lower())

    # Check if the sorted versions of both strings are equal
    return cleaned_string1 == cleaned_string2

# Example usage
str1 = "Listen"
str2 = "Silent"

if are_anagrams(str1, str2):
    print(f"'{str1}' and '{str2}' are anagrams.")
else:
    print(f"'{str1}' and '{str2}' are not anagrams.")

'Listen' and 'Silent' are anagrams.

#5.Write a code to find all occurrences of a given substring within another string.

In [ ]:
def find_all_occurrences(main_string, substring):
    # Initialize an empty list to store the positions of occurrences
    occurrences = []
    # Initialize the start index
    start = 0

    # Loop to find all occurrences of the substring
    while True:
        # Find the index of the substring in the main string starting from 'start'
        index = main_string.find(substring, start)

        # If the substring is found, add the index to the list
        if index != -1:
            occurrences.append(index)
            # Update the start index to search for the next occurrence
            start = index + 1
        else:
            # Break the loop if no more occurrences are found
            break

    return occurrences

# Example usage
main_string = "This is a test string, and this is another test string."
substring = "test"

occurrences = find_all_occurrences(main_string, substring)
print(f"Occurrences of '{substring}' in the main string: {occurrences}")

Occurrences of 'test' in the main string: [10, 43]

#6.Write a code to perform basic string compression uisng the counts of repeated characters.

In [ ]:
def compress_string(input_string):
    # Initialize variables to store the compressed string and the count of characters
    compressed = []
    count = 1

    # Iterate through the string characters
    for i in range(1, len(input_string)):
        # If the current character is the same as the previous one, increment the count
        if input_string[i] == input_string[i - 1]:
            count += 1
        else:
            # Otherwise, add the previous character and its count to the compressed list
            compressed.append(input_string[i - 1] + str(count))
            # Reset the count for the new character
            count = 1

    # Add the last character and its count
    compressed.append(input_string[-1] + str(count))

    # Join the compressed list into a single string
    compressed_string = ''.join(compressed)

    # Return the original string if compression does not reduce the length
    return compressed_string if len(compressed_string) < len(input_string) else input_string

# Example usage
input_string = "aabcccccaaa"
compressed = compress_string(input_string)
print(f"Compressed string: {compressed}")

Compressed string: a2b1c5a3

#7.Write a code to determine if a string has all unique characters.

In [ ]:
def has_all_unique_characters(input_string):
    # Create an empty set to store characters
    char_set = set()

    # Iterate through each character in the input string
    for char in input_string:
        # If the character is already in the set, it means it's not unique
        if char in char_set:
            return False
        # Add the character to the set
        char_set.add(char)

    # If no duplicate character is found, return True
    return True

# Example usage
input_string = "abcdefg"
result = has_all_unique_characters(input_string)
print(f"Does '{input_string}' have all unique characters? {result}")

Does 'abcdefg' have all unique characters? True

#8.Write  a code to convert a given string to uppercase or lowercase.

In [ ]:
def convert_case(input_string, to_upper=True):
    # Convert the string to uppercase if 'to_upper' is True, otherwise convert to lowercase
    if to_upper:
        return input_string.upper()
    else:
        return input_string.lower()

# Example usage
input_string = "Hello, World!"

# Convert to uppercase
uppercase_string = convert_case(input_string, to_upper=True)
print(f"Uppercase: {uppercase_string}")

# Convert to lowercase
lowercase_string = convert_case(input_string, to_upper=False)
print(f"Lowercase: {lowercase_string}")

Uppercase: HELLO, WORLD!
Lowercase: hello, world!

#9.Write a code to count the number of words in a string.

In [ ]:
def count_words(input_string):
    # Split the string by whitespace and filter out empty strings
    words = [word for word in input_string.split() if word]
    # Return the number of words
    return len(words)

# Example usage
input_string = "This is an example string with several words."
word_count = count_words(input_string)
print(f"Number of words in the string: {word_count}")

Number of words in the string: 8

#10.Write a code to concatenate two strings without using the + operator.

In [ ]:
def concatenate_strings(string1, string2):
    # Use the join() method to concatenate the strings
    return ''.join([string1, string2])

# Example usage
string1 = "Hello, "
string2 = "World!"
concatenated_string = concatenate_strings(string1, string2)
print(f"Concatenated string: {concatenated_string}")

Concatenated string: Hello, World!

#11.Write a code to remove all occurrences of a specific element from a list.

In [ ]:
def remove_all_occurrences(lst, element):
    # Use a list comprehension to create a new list without the specified element
    return [item for item in lst if item != element]

# Example usage
my_list = [1, 2, 3, 4, 2, 5, 2]
element_to_remove = 2
new_list = remove_all_occurrences(my_list, element_to_remove)
print(f"List after removing all occurrences of {element_to_remove}: {new_list}")

List after removing all occurrences of 2: [1, 3, 4, 5]

#12.Implement a code to find the second largest number in  a given list of intergers.

In [ ]:
def find_second_largest(nums):
    # Remove duplicates by converting the list to a set
    nums = list(set(nums))

    if len(nums) < 2:
        return "List must contain at least two unique numbers."

    # Sort the list in descending order
    nums.sort(reverse=True)

    # Return the second element (second largest number)
    return nums[1]

# Example usage
numbers = [10, 20, 4, 45, 99, 99, 20]
second_largest = find_second_largest(numbers)
print(f"The second largest number is: {second_largest}")

The second largest number is: 45

#13.Create a code to count the occurrences of each element in a list and return a distioonary with elements as keys and their counts as values.

In [ ]:
def count_occurrences(lst):
    # Initialize an empty dictionary
    count_dict = {}

    # Loop through each element in the list
    for item in lst:
        # If the element is already in the dictionary, increment its count
        if item in count_dict:
            count_dict[item] += 1
        # Otherwise, add the element to the dictionary with a count of 1
        else:
            count_dict[item] = 1

    return count_dict

# Example usage
elements = [10, 20, 10, 30, 20, 40, 50, 20, 30]
occurrences = count_occurrences(elements)
print(occurrences)

{10: 2, 20: 3, 30: 2, 40: 1, 50: 1}

#14.Write a code to reverse a list in-place without using any built-in reverse functions.

In [ ]:
def reverse_list(lst):
    # Initialize two pointers, one at the beginning and one at the end
    start = 0
    end = len(lst) - 1

    # Swap elements while start is less than end
    while start < end:
        # Swap the elements
        lst[start], lst[end] = lst[end], lst[start]

        # Move the pointers towards each other
        start += 1
        end -= 1

# Example usage
elements = [10, 20, 30, 40, 50]
print(f"Original list: {elements}")
reverse_list(elements)
print(f"Reversed list: {elements}")

Original list: [10, 20, 30, 40, 50]
Reversed list: [50, 40, 30, 20, 10]

#15.Implement a code to find and remove duplicates from a list while preserving the original order of elements.

In [ ]:
def remove_duplicates(lst):
    # Initialize an empty list to store unique elements
    unique_list = []
    # Initialize a set to track seen elements
    seen = set()

    # Loop through each element in the list
    for item in lst:
        # If the item has not been seen before, add it to the unique list and mark it as seen
        if item not in seen:
            unique_list.append(item)
            seen.add(item)

    return unique_list

# Example usage
elements = [10, 20, 10, 30, 40, 50, 20, 30]
unique_elements = remove_duplicates(elements)
print(f"Original list: {elements}")
print(f"List after removing duplicates: {unique_elements}")

Original list: [10, 20, 10, 30, 40, 50, 20, 30]
List after removing duplicates: [10, 20, 30, 40, 50]

#16.Create a code to check if a given list is sorted(either in ascending or descending order) or not.

In [ ]:
def is_sorted(lst):
    # Check if the list is sorted in ascending order
    ascending = all(lst[i] <= lst[i + 1] for i in range(len(lst) - 1))

    # Check if the list is sorted in descending order
    descending = all(lst[i] >= lst[i + 1] for i in range(len(lst) - 1))

    # Return the result
    if ascending:
        return "List is sorted in ascending order."
    elif descending:
        return "List is sorted in descending order."
    else:
        return "List is not sorted."

# Example usage
elements1 = [10, 20, 30, 40, 50]
elements2 = [50, 40, 30, 20, 10]
elements3 = [10, 50, 30, 20, 40]

print(is_sorted(elements1))  # Ascending
print(is_sorted(elements2))  # Descending
print(is_sorted(elements3))  # Not sorted

List is sorted in ascending order.
List is sorted in descending order.
List is not sorted.

#17.Write a code to merge two sorted lists into a single sorted list.

In [ ]:
def merge_sorted_lists(list1, list2):
    # Initialize pointers for both lists
    i, j = 0, 0
    # Initialize an empty list to store the merged result
    merged_list = []

    # Traverse both lists and merge them
    while i < len(list1) and j < len(list2):
        if list1[i] <= list2[j]:
            merged_list.append(list1[i])
            i += 1
        else:
            merged_list.append(list2[j])
            j += 1

    # If any elements are left in list1, add them
    while i < len(list1):
        merged_list.append(list1[i])
        i += 1

    # If any elements are left in list2, add them
    while j < len(list2):
        merged_list.append(list2[j])
        j += 1

    return merged_list

# Example usage
sorted_list1 = [1, 3, 5, 7]
sorted_list2 = [2, 4, 6, 8]

merged_list = merge_sorted_lists(sorted_list1, sorted_list2)
print(f"Merged sorted list: {merged_list}")

Merged sorted list: [1, 2, 3, 4, 5, 6, 7, 8]

#18.Implement a code to find intersection of two given lists.

In [ ]:
def find_intersection(list1, list2):
    # Convert both lists to sets and find their intersection
    intersection = set(list1) & set(list2)

    # Convert the intersection set back to a list
    return list(intersection)

# Example usage
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]

intersection = find_intersection(list1, list2)
print(f"Intersection of the lists: {intersection}")

Intersection of the lists: [4, 5]

#19.Create a code to find the union of two lists without duplicates

In [ ]:
def find_union(list1, list2):
    # Convert both lists to sets and find their union
    union = set(list1) | set(list2)

    # Convert the union set back to a list
    return list(union)

# Example usage
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]

union = find_union(list1, list2)
print(f"Union of the lists without duplicates: {union}")

Union of the lists without duplicates: [1, 2, 3, 4, 5, 6, 7, 8]

#20.Write  a code to shuffle a given list randomly without using any built-in functions.

In [ ]:
import random

def shuffle_list(lst):
    # Get the length of the list
    n = len(lst)

    # Iterate over the list
    for i in range(n):
        # Generate a random index between the current index and the last index
        j = random.randint(i, n - 1)

        # Swap the current element with the randomly chosen element
        lst[i], lst[j] = lst[j], lst[i]

    return lst

# Example usage
elements = [1, 2, 3, 4, 5]
print(f"Original list: {elements}")
shuffled_list = shuffle_list(elements)
print(f"Shuffled list: {shuffled_list}")

Original list: [1, 2, 3, 4, 5]
Shuffled list: [3, 2, 1, 5, 4]

#21.Write a code that takes two tuples as input and returns a new tuple containing elements that are common to both input tuples.

In [ ]:
def common_elements(tuple1, tuple2):
    # Convert both tuples to sets to find common elements
    common_set = set(tuple1) & set(tuple2)

    # Convert the set back to a tuple
    return tuple(common_set)

# Example usage
tuple1 = (1, 2, 3, 4, 5)
tuple2 = (4, 5, 6, 7, 8)

common_tuple = common_elements(tuple1, tuple2)
print(f"Common elements in both tuples: {common_tuple}")

Common elements in both tuples: (4, 5)

#22.Create a code that prompts the user to enter two sets of integer separated by commas.then,print the inetrsection of these two sets.

In [ ]:
def get_set_from_input(prompt):
    # Prompt the user to enter a set of integers separated by commas
    user_input = input(prompt)

    # Convert the input string into a list of strings and then into a set of integers
    num_list = user_input.split(',')
    num_set = set(int(num) for num in num_list)

    return num_set

def main():
    # Get the two sets from user input
    set1 = get_set_from_input("Enter the first set of integers separated by commas: ")
    set2 = get_set_from_input("Enter the second set of integers separated by commas: ")

    # Find the intersection of the two sets
    intersection = set1 & set2

    # Print the intersection
    print(f"Intersection of the two sets: {intersection}")

if __name__ == "__main__":
    main()

Enter the first set of integers separated by commas: 6,7
Enter the second set of integers separated by commas: 7,8
Intersection of the two sets: {7}

#23.Write a code to concatenate two tuples.The function should take two tuples as input and return a new tuple containing elements from both input tuples.

In [ ]:
def concatenate_tuples(tuple1, tuple2):
    # Concatenate the two tuples
    result_tuple = tuple1 + tuple2

    return result_tuple

# Example usage
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

concatenated_tuple = concatenate_tuples(tuple1, tuple2)
print(f"Concatenated tuple: {concatenated_tuple}")

Concatenated tuple: (1, 2, 3, 4, 5, 6)

#24.Develop a code that prompts the user to input two sets of strings. Then,print the elements that are present in the first set but not in the second set.

In [ ]:
def get_set_from_input(prompt):
    # Prompt the user to enter a set of strings separated by commas
    user_input = input(prompt)

    # Convert the input string into a list of strings and then into a set of strings
    str_list = user_input.split(',')
    str_set = set(s.strip() for s in str_list)

    return str_set

def main():
    # Get the two sets of strings from user input
    set1 = get_set_from_input("Enter the first set of strings separated by commas: ")
    set2 = get_set_from_input("Enter the second set of strings separated by commas: ")

    # Find elements in the first set that are not in the second set
    difference = set1 - set2

    # Print the result
    print(f"Elements in the first set but not in the second set: {difference}")

if __name__ == "__main__":
    main()

Enter the first set of strings separated by commas: "apple","kiwi","orange"
Enter the second set of strings separated by commas: "apple","grapes"
Elements in the first set but not in the second set: {'"orange"', '"kiwi"'}

#25.Create  a code that takes a tuple and two integers as input. The function should return a new tuple containing elements from the original tuple within the specified range of indices.

In [ ]:
def slice_tuple(original_tuple, start_index, end_index):
    # Ensure the indices are within the bounds of the tuple
    if start_index < 0:
        start_index = 0
    if end_index > len(original_tuple):
        end_index = len(original_tuple)

    # Return the sliced tuple
    return original_tuple[start_index:end_index]

# Example usage
original_tuple = (10, 20, 30, 40, 50, 60, 70)
start = 2
end = 5

sliced_tuple = slice_tuple(original_tuple, start, end)
print(f"Original tuple: {original_tuple}")
print(f"Sliced tuple from index {start} to {end}: {sliced_tuple}")

Original tuple: (10, 20, 30, 40, 50, 60, 70)
Sliced tuple from index 2 to 5: (30, 40, 50)

#26.Write a code that prompts the user to input two sets of characters.Then, print the union of these two sets.

In [ ]:
def get_set_from_input(prompt):
    # Prompt the user to enter a set of characters separated by commas
    user_input = input(prompt)

    # Convert the input string into a list of characters and then into a set
    char_list = user_input.split(',')
    char_set = set(char.strip() for char in char_list)

    return char_set

def main():
    # Get the two sets of characters from user input
    set1 = get_set_from_input("Enter the first set of characters separated by commas: ")
    set2 = get_set_from_input("Enter the second set of characters separated by commas: ")

    # Find the union of the two sets
    union = set1 | set2

    # Print the result
    print(f"Union of the two sets: {union}")

if __name__ == "__main__":
    main()

Enter the first set of characters separated by commas: a,b,c
Enter the second set of characters separated by commas: b,c,d
Union of the two sets: {'a', 'b', 'd', 'c'}

#27.Develop a code that takes a tuple of integers as input. The function should return the maximum and minimum values from the tuple using tuple unpacking.

In [ ]:
def find_max_min(tpl):
    # Ensure the tuple is not empty
    if not tpl:
        raise ValueError("Tuple is empty. Cannot determine max and min values.")

    # Find maximum and minimum values
    max_value = max(tpl)
    min_value = min(tpl)

    # Return the max and min values using tuple unpacking
    return max_value, min_value

# Example usage
input_tuple = (10, 20, 30, 40, 50)

max_value, min_value = find_max_min(input_tuple)
print(f"Input tuple: {input_tuple}")
print(f"Maximum value: {max_value}")
print(f"Minimum value: {min_value}")

Input tuple: (10, 20, 30, 40, 50)
Maximum value: 50
Minimum value: 10

#28.Create a code that defines two sets of integers.Then, print the union, intersection and difference of these two sets.

In [ ]:
def main():
    # Define two sets of integers
    set1 = {1, 2, 3, 4, 5}
    set2 = {4, 5, 6, 7, 8}

    # Calculate the union of the two sets
    union = set1 | set2

    # Calculate the intersection of the two sets
    intersection = set1 & set2

    # Calculate the difference between the two sets
    difference_set1_set2 = set1 - set2
    difference_set2_set1 = set2 - set1

    # Print the results
    print(f"Set 1: {set1}")
    print(f"Set 2: {set2}")
    print(f"Union of Set 1 and Set 2: {union}")
    print(f"Intersection of Set 1 and Set 2: {intersection}")
    print(f"Difference (Set 1 - Set 2): {difference_set1_set2}")
    print(f"Difference (Set 2 - Set 1): {difference_set2_set1}")

if __name__ == "__main__":
    main()

Set 1: {1, 2, 3, 4, 5}
Set 2: {4, 5, 6, 7, 8}
Union of Set 1 and Set 2: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection of Set 1 and Set 2: {4, 5}
Difference (Set 1 - Set 2): {1, 2, 3}
Difference (Set 2 - Set 1): {8, 6, 7}

#29.Write a code that takes a tuple and an element as input.the function should return the count of occurrences of given element in the tuple.

In [ ]:
def count_occurrences(tpl, element):
    # Count the occurrences of the element in the tuple
    count = tpl.count(element)

    return count

# Example usage
input_tuple = (1, 2, 3, 4, 2, 5, 2)
element_to_count = 2

occurrences = count_occurrences(input_tuple, element_to_count)
print(f"Tuple: {input_tuple}")
print(f"Element to count: {element_to_count}")
print(f"Count of occurrences: {occurrences}")

Tuple: (1, 2, 3, 4, 2, 5, 2)
Element to count: 2
Count of occurrences: 3

#30.Develop a code that prompts the user to input two sets of strings.Then, print the symmetric difference of these two sets.

In [ ]:
def get_set_from_input(prompt):
    # Prompt the user to enter a set of strings separated by commas
    user_input = input(prompt)

    # Convert the input string into a list of strings and then into a set of strings
    str_list = user_input.split(',')
    str_set = set(s.strip() for s in str_list)

    return str_set

def main():
    # Get the two sets of strings from user input
    set1 = get_set_from_input("Enter the first set of strings separated by commas: ")
    set2 = get_set_from_input("Enter the second set of strings separated by commas: ")

    # Find the symmetric difference of the two sets
    symmetric_difference = set1 ^ set2

    # Print the result
    print(f"Symmetric difference of the two sets: {symmetric_difference}")

if __name__ == "__main__":
    main()

Enter the first set of strings separated by commas: a,b,c
Enter the second set of strings separated by commas: b,d
Symmetric difference of the two sets: {'a', 'c', 'd'}

#31.Write a code that takes a list of words as input and returns a dictionary where the keys are unique words and the values are the frequencies of those words in the input list.

In [ ]:
def word_frequencies(words):
    frequency_dict = {}

    for word in words:
        # Convert the word to lower case to ensure case-insensitivity
        word = word.lower()
        if word in frequency_dict:
            # Increment the count if the word is already in the dictionary
            frequency_dict[word] += 1
        else:
            # Add the word to the dictionary with count 1 if it is not present
            frequency_dict[word] = 1

    return frequency_dict

# Example usage
words_list = ['apple', 'banana', 'Apple', 'orange', 'banana', 'apple', 'Orange']
frequency_dict = word_frequencies(words_list)
print(f"Word frequencies: {frequency_dict}")

Word frequencies: {'apple': 3, 'banana': 2, 'orange': 2}

#32.Write a code that takes two dictionaries as input and merges them into a single dictionary.If there are common keys,the values should be added together.

In [ ]:
def merge_dictionaries(dict1, dict2):
    # Create a new dictionary to store the merged result
    merged_dict = {}

    # Add all key-value pairs from the first dictionary
    for key, value in dict1.items():
        merged_dict[key] = value

    # Add all key-value pairs from the second dictionary
    for key, value in dict2.items():
        if key in merged_dict:
            # If the key already exists, add the values
            merged_dict[key] += value
        else:
            # Otherwise, add the new key-value pair
            merged_dict[key] = value

    return merged_dict

# Example usage
dict1 = {'a': 10, 'b': 20, 'c': 30}
dict2 = {'b': 5, 'c': 10, 'd': 15}

merged_dict = merge_dictionaries(dict1, dict2)
print(f"Merged dictionary: {merged_dict}")

Merged dictionary: {'a': 10, 'b': 25, 'c': 40, 'd': 15}

#33.Write a code to access a value in a nested dictionary.The function should take the dictionary and a list of keys as input and return the corresponding value.If any keys do not exist in the dictionary, the function should return None.

In [ ]:
def access_nested_value(d, keys):
    # Initialize current dictionary level
    current = d

    for key in keys:
        # Check if the key exists in the current dictionary level
        if isinstance(current, dict) and key in current:
            current = current[key]
        else:
            # Return None if key does not exist
            return None

    return current

# Example usage
nested_dict = {
    'a': {
        'b': {
            'c': 42
        }
    },
    'x': {
        'y': 100
    }
}

# Access value using a list of keys
keys = ['a', 'b', 'c']
value = access_nested_value(nested_dict, keys)
print(f"Value at keys {keys}: {value}")

# Access value with non-existent key
keys = ['a', 'b', 'z']
value = access_nested_value(nested_dict, keys)
print(f"Value at keys {keys}: {value}")

# Access value using another set of keys
keys = ['x', 'y']
value = access_nested_value(nested_dict, keys)
print(f"Value at keys {keys}: {value}")

Value at keys ['a', 'b', 'c']: 42
Value at keys ['a', 'b', 'z']: None
Value at keys ['x', 'y']: 100

#34.Write a code that takes a dictionary as input and returns a sorted version of it based on the values.You can choose whether to sort in ascending or descending order.

In [ ]:
def sort_dictionary_by_values(d, reverse=False):
    # Sort the dictionary by values and return a new dictionary
    sorted_dict = dict(sorted(d.items(), key=lambda item: item[1], reverse=reverse))

    return sorted_dict

# Example usage
input_dict = {
    'apple': 3,
    'banana': 1,
    'cherry': 2,
    'date': 4
}

# Sort in ascending order
sorted_dict_asc = sort_dictionary_by_values(input_dict)
print(f"Dictionary sorted by values (ascending): {sorted_dict_asc}")

# Sort in descending order
sorted_dict_desc = sort_dictionary_by_values(input_dict, reverse=True)
print(f"Dictionary sorted by values (descending): {sorted_dict_desc}")

Dictionary sorted by values (ascending): {'banana': 1, 'cherry': 2, 'apple': 3, 'date': 4}
Dictionary sorted by values (descending): {'date': 4, 'apple': 3, 'cherry': 2, 'banana': 1}

#35.Write a code that inverts a dictionary,swapping keys and values.Ensure that the inverted dictionary correctly handles cases where multiple keys have the same value by storing the keys as a list in the inverted dictionary.

In [ ]:
def invert_dictionary(original_dict):
    inverted_dict = {}

    for key, value in original_dict.items():
        # If the value is already a key in the inverted dictionary, append the key to the list of keys
        if value in inverted_dict:
            if isinstance(inverted_dict[value], list):
                inverted_dict[value].append(key)
            else:
                inverted_dict[value] = [inverted_dict[value], key]
        else:
            # If the value is not in the inverted dictionary, create a new entry with the current key
            inverted_dict[value] = key

    return inverted_dict

# Example usage
original_dict = {
    'a': 1,
    'b': 2,
    'c': 1,
    'd': 3
}

inverted_dict = invert_dictionary(original_dict)
print(f"Original dictionary: {original_dict}")
print(f"Inverted dictionary: {inverted_dict}")

Original dictionary: {'a': 1, 'b': 2, 'c': 1, 'd': 3}
Inverted dictionary: {1: ['a', 'c'], 2: 'b', 3: 'd'}