<a href="https://colab.research.google.com/github/UVDivyaSree/PW_Skills_Assignments/blob/main/PandaAdvance_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
df.shape

(891, 12)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [9]:
 df[0:100:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.8625,E46,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,347742,11.1333,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,8.0500,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,7.8542,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.00,1,0,345763,18.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.00,0,0,239865,26.0000,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,27.7208,NaN,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.00,1,0,PC 17604,82.1708,NaN,C
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.00,2,0,345764,18.0000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,7546,9.4750,NaN,S
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.00,0,0,330958,7.8792,NaN,Q
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
50,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,PC 17572,76.7292,D33,C
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,61.9792,B30,C
56,57,1,2,"Rugg, Miss. Emily",female,21.00,0,0,C.A. 31026,10.5000,NaN,S
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,7.2292,NaN,C
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.00,1,0,36973,83.4750,C83,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,10.5000,F33,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.00,0,0,C.A. 33111,10.5000,NaN,S
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,73.5000,NaN,S
74,75,1,3,"Bing, Mr. Lee",male,32.00,0,0,1601,56.4958,NaN,S
76,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
80,81,0,3,"Waelens, Mr. Achille",male,22.00,0,0,345767,9.0000,NaN,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
86,87,0,3,"Ford, Mr. William Neal",male,16.00,1,3,W./C. 6608,34.3750,NaN,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
90,91,0,3,"Christmann, Mr. Emil",male,29.00,0,0,343276,8.0500,NaN,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.00,1,0,W.E.P. 5734,61.1750,E31,S
94,95,0,3,"Coxon, Mr. Daniel",male,59.00,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542,A5,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.00,0,1,231919,23.0000,NaN,S

In [10]:
 df[0:100:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.0,0,0,C.A. 33111,10.5000,NaN,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S
80,81,0,3,"Waelens, Mr. Achille",male,22.0,0,0,345767,9.0000,NaN,S
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.0,3,0,3101278,15.8500,NaN,S
90,91,0,3,"Christmann, Mr. Emil",male,29.0,0,0,343276,8.0500,NaN,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S

In [11]:
#Access rws and columns of a dtaframes

#!Implicit/integer/internal indexing>>i lock
#2.explicit or named indexing

In [12]:
#iloc
df.iloc[0:3] #start from 0 and go till 2  (3-1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [13]:
df.loc[0:3] #loc is used for named index  --iloc is used for int index

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [14]:
df.iloc[0:2,['Name','Sex']]  #willnthrow an index
#iloc should requires numeric indexes

IndexError: .iloc requires numeric indexers, got ['Name' 'Sex']

In [15]:
df.loc[0:2,['Name','Sex']]

                                                Name     Sex
0                            Braund, Mr. Owen Harris    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                             Heikkinen, Miss. Laina  female

In [16]:
#if you want to use only iloc
df.iloc[0:2,3:5]

                                                Name     Sex
0                            Braund, Mr. Owen Harris    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female

In [17]:
df.iloc[0:2,3:6]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0

In [18]:
list(df["Name"][2:5])

['Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry']

In [21]:
s=pd.Series(list(df["Name"][2:5]),index=['a','b','c'])

In [22]:
s

a                          Heikkinen, Miss. Laina
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)
c                        Allen, Mr. William Henry
dtype: object

In [30]:
s1=pd.Series(list(df["Name"][5:8]))

In [31]:
s1

0                  Moran, Mr. James
1           McCarthy, Mr. Timothy J
2    Palsson, Master. Gosta Leonard
dtype: object

In [25]:
#series with diff indexes and dataframes cannot bbe concatnated using+ function
s + s1

a    NaN
b    NaN
c    NaN
0    NaN
1    NaN
2    NaN
dtype: object

In [32]:
#if you keep indexes same,then for series concatenation can happen
s1=pd.Series(list(df["Name"][5:8]),index=['a','b','c'])
s1

a                  Moran, Mr. James
b           McCarthy, Mr. Timothy J
c    Palsson, Master. Gosta Leonard
dtype: object

In [27]:
s

a                          Heikkinen, Miss. Laina
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)
c                        Allen, Mr. William Henry
dtype: object

In [34]:
s +  s1

a               Heikkinen, Miss. LainaMoran, Mr. James
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)Mc...
c    Allen, Mr. William HenryPalsson, Master. Gosta...
dtype: object

In [35]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [41]:
#TOo drop a column
#df.drop("PassengerId")  by default it assume that they are rows
df.drop("PassengerId",axis=1,inplace=True)
 #axis=1 means it assumes it is acolumn  && implace= true means modify the original dtaframe

In [42]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [43]:
#how to drop a row
df.drop(1,inplace=True)

In [44]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [45]:
#After dropping to get consecutive index
df.reset_index(drop=True)  #drop true to eliminate the original index which is not consecutive

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
4,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
886,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
887,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
889,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [46]:
#set a new index
df.set_index("Name",inplace=True)

In [47]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [50]:
df.loc["Dooley, Mr. Patrick"]

Survived         0
Pclass           3
Sex           male
Age           32.0
SibSp            0
Parch            0
Ticket      370376
Fare          7.75
Cabin          NaN
Embarked         Q
Name: Dooley, Mr. Patrick, dtype: object

In [51]:
df.reset_index()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [54]:
#can we make a dataframe from a dictionary
d = {"key1" : [2,3,4],
    "key2" : [5,6,7],"key3" : [8,9,10]}
d

{'key1': [2, 3, 4], 'key2': [5, 6, 7], 'key3': [8, 9, 10]}

In [55]:
pd.DataFrame(d)

   key1  key2  key3
0     2     5     8
1     3     6     9
2     4     7    10

In [56]:
#in form of tuples
d = {"key1" : (2,3,4),
    "key2" : (5,6,7),"key3" : (8,9,10)}

In [57]:
pd.DataFrame(d)

   key1  key2  key3
0     2     5     8
1     3     6     9
2     4     7    10

In [58]:
df1=pd.read_csv("taxonomy.csv")

In [59]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [60]:
df1.shape

(290, 4)

In [61]:
df1.describe()

       taxonomy_id          name  parent_id       parent_name
count          290           290        279               279
unique         290           183         60                50
top            101  Nursing Home  106-06-07  Health Education
freq             1             4         11                15

In [62]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   taxonomy_id  290 non-null    object
 1   name         290 non-null    object
 2   parent_id    279 non-null    object
 3   parent_name  279 non-null    object
dtypes: object(4)
memory usage: 9.2+ KB

In [64]:
df1.isnull().sum()

taxonomy_id     0
name            0
parent_id      11
parent_name    11
dtype: int64

In [65]:
df1.shape

(290, 4)

In [66]:
df1.dropna()  #remove null value from the rows

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5     101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [67]:
df1.dropna(axis=1)  #remove null value from the columns

    taxonomy_id                          name
0           101                     Emergency
1        101-01             Disaster Response
2        101-02                Emergency Cash
3     101-02-01             Help Pay for Food
4     101-02-02       Help Pay for Healthcare
..          ...                           ...
285   111-01-07              Workplace Rights
286      111-02                     Mediation
287      111-03                        Notary
288      111-04                Representation
289      111-05  Translation & Interpretation

[290 rows x 2 columns]

In [69]:
df1[['name']].dropna(axis=1)  #for 1 column

                             name
0                       Emergency
1               Disaster Response
2                  Emergency Cash
3               Help Pay for Food
4         Help Pay for Healthcare
..                            ...
285              Workplace Rights
286                     Mediation
287                        Notary
288                Representation
289  Translation & Interpretation

[290 rows x 1 columns]

In [ ]:
#imputation>>replacing missing values with some values
#num data>>mean,median >>if outlier/extreme /abnormal value treatment is done
#then you can use mean othervise median
#for categorical data we can use mode
#impute missing with some constant,i.e.0

In [70]:
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [71]:
df1.fillna("somevalue")

    taxonomy_id                          name  parent_id           parent_name
0           101                     Emergency  somevalue             somevalue
1        101-01             Disaster Response        101             Emergency
2        101-02                Emergency Cash        101             Emergency
3     101-02-01             Help Pay for Food     101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare     101-02        Emergency Cash
..          ...                           ...        ...                   ...
285   111-01-07              Workplace Rights     111-01  Advocacy & Legal Aid
286      111-02                     Mediation        111                 Legal
287      111-03                        Notary        111                 Legal
288      111-04                Representation        111                 Legal
289      111-05  Translation & Interpretation        111                 Legal

[290 rows x 4 columns]

In [72]:
df1.fillna(0)

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency         0                     0
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [73]:
data1={"A":[1,2,None,4,5,None,7,8,9,10],
       "B":[None,11,12,13,None,15,16,None,18,19]}
df2=pd.DataFrame(data1)

In [74]:
df2

      A     B
0   1.0   NaN
1   2.0  11.0
2   NaN  12.0
3   4.0  13.0
4   5.0   NaN
5   NaN  15.0
6   7.0  16.0
7   8.0   NaN
8   9.0  18.0
9  10.0  19.0

In [75]:
df2['A'].mean()

5.75

In [76]:
df2["A"].fillna(df2['A'].mean())

0     1.00
1     2.00
2     5.75
3     4.00
4     5.00
5     5.75
6     7.00
7     8.00
8     9.00
9    10.00
Name: A, dtype: float64

In [77]:
df2['A'].median()

6.0

In [78]:
df2["A"].fillna(df2['A'].median())

0     1.0
1     2.0
2     6.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
Name: A, dtype: float64

In [79]:
df2

      A     B
0   1.0   NaN
1   2.0  11.0
2   NaN  12.0
3   4.0  13.0
4   5.0   NaN
5   NaN  15.0
6   7.0  16.0
7   8.0   NaN
8   9.0  18.0
9  10.0  19.0

In [80]:
df2.fillna("some value")

            A           B
0         1.0  some value
1         2.0        11.0
2  some value        12.0
3         4.0        13.0
4         5.0  some value
5  some value        15.0
6         7.0        16.0
7         8.0  some value
8         9.0        18.0
9        10.0        19.0

In [81]:
df2.fillna(0)

      A     B
0   1.0   0.0
1   2.0  11.0
2   0.0  12.0
3   4.0  13.0
4   5.0   0.0
5   0.0  15.0
6   7.0  16.0
7   8.0   0.0
8   9.0  18.0
9  10.0  19.0

In [83]:
df2.fillna(method="ffill")  #forwardfillsatrt seeing from the bottom of the d atafrme and fill with next observed value

<ipython-input-83-495f4bfbfd9b>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method="ffill")  #forwardfill

      A     B
0   1.0   NaN
1   2.0  11.0
2   2.0  12.0
3   4.0  13.0
4   5.0  13.0
5   5.0  15.0
6   7.0  16.0
7   8.0  16.0
8   9.0  18.0
9  10.0  19.0

In [84]:
df2.fillna(method="bfill")  #backwardfillsatrt seeing from the top of the d atafrme and fill with next observed value

<ipython-input-84-fea03a43144c>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method="bfill")  #backwardfillsatrt seeing from the top of the d atafrme and fill with next observed value

      A     B
0   1.0  11.0
1   2.0  11.0
2   4.0  12.0
3   4.0  13.0
4   5.0  15.0
5   7.0  15.0
6   7.0  16.0
7   8.0  18.0
8   9.0  18.0
9  10.0  19.0

In [86]:
 #checking duplicte rows
df2.duplicated().sum()

0

In [87]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [88]:
df.duplicated().sum()

15

In [93]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [95]:
df.Age.describe()

count    713.000000
mean      29.687475
std       14.533361
min        0.420000
25%       20.000000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [96]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [97]:
df.reset_index(inplace=True)

In [98]:
df

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [100]:
#Q .. what is the avg fare paid by the people who survived
df[df['Survived'] ==1]

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
7,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1,3,female,27.0,0,2,347742,11.1333,NaN,S
8,"Nasser, Mrs. Nicholas (Adele Achem)",1,2,female,14.0,1,0,237736,30.0708,NaN,C
9,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
...,...,...,...,...,...,...,...,...,...,...,...
874,"Najib, Miss. Adele Kiamie ""Jane""",1,3,female,15.0,0,0,2667,7.2250,NaN,C
878,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,female,56.0,0,1,11767,83.1583,C50,C
879,"Shelley, Mrs. William (Imanita Parrish Hall)",1,2,female,25.0,0,1,230433,26.0000,NaN,S
886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C

In [101]:
df[df['Survived'] ==1]["Fare"]

1       7.9250
2      53.1000
7      11.1333
8      30.0708
9      16.7000
        ...
874     7.2250
878    83.1583
879    26.0000
886    30.0000
888    30.0000
Name: Fare, Length: 341, dtype: float64

In [102]:
df[df['Survived'] ==1]["Fare"].mean()

48.32828768328446

In [103]:
#avvd fare who didnt survived
df[df['Survived'] ==0]["Fare"].mean()

22.117886885245902

In [105]:
#avg age who survived
df[df['Survived'] ==0]["Age"].mean()

30.62617924528302

In [ ]:
#what if i as avg age who survived ?change fare to age
#what if i ask min,max,std of age and fare in one result
#groupby

In [107]:
df.groupby("Survived").mean(numeric_only = True)

            Pclass        Age     SibSp     Parch       Fare
Survived
0         2.531876  30.626179  0.553734  0.329690  22.117887
1         1.953079  28.310277  0.472141  0.466276  48.328288

![pandas.png]()

In [108]:
df.groupby("Survived").sum(numeric_only = True)

          Pclass       Age  SibSp  Parch        Fare
Survived
0           1390  12985.50    304    181  12142.7199
1            666   8181.67    161    159  16479.9461

In [110]:
df.groupby("Survived").describe()

         Pclass                                                 Age  \
          count      mean       std  min  25%  50%  75%  max  count
Survived
0         549.0  2.531876  0.735805  1.0  2.0  3.0  3.0  3.0  424.0
1         341.0  1.953079  0.863047  1.0  1.0  2.0  3.0  3.0  289.0

                     ... Parch        Fare                             \
               mean  ...   75%  max  count       mean        std  min
Survived             ...
0         30.626179  ...   0.0  6.0  549.0  22.117887  31.388207  0.0
1         28.310277  ...   1.0  5.0  341.0  48.328288  66.683277  0.0


              25%   50%   75%       max
Survived
0          7.8542  10.5  26.0  263.0000
1         12.4750  26.0  57.0  512.3292

[2 rows x 40 columns]

In [111]:
df[["Survived","Fare"]]

     Survived     Fare
0           0   7.2500
1           1   7.9250
2           1  53.1000
3           0   8.0500
4           0   8.4583
..        ...      ...
885         0  13.0000
886         1  30.0000
887         0  23.4500
888         1  30.0000
889         0   7.7500

[890 rows x 2 columns]

In [112]:
import numpy as np
df.groupby(["Survived"])["Fare"].agg([min,'max','mean','median','count',np.std,'var'])

<ipython-input-112-d702bd5e155d>:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(["Survived"])["Fare"].agg([min,'max','mean','median','count',np.std,'var'])
<ipython-input-112-d702bd5e155d>:2: FutureWarning: The provided callable <function std at 0x7c63fe4116c0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  df.groupby(["Survived"])["Fare"].agg([min,'max','mean','median','count',np.std,'var'])

          min       max       mean  median  count        std          var
Survived
0         0.0  263.0000  22.117887    10.5    549  31.388207   985.219509
1         0.0  512.3292  48.328288    26.0    341  66.683277  4446.659477

In [114]:
#how any passengers survived or not survived for each gender and passenger class
df.groupby(["Sex","Pclass"])["Survived"].sum()

Sex     Pclass
female  1         90
        2         70
        3         72
male    1         45
        2         17
        3         47
Name: Survived, dtype: int64

In [115]:
df.groupby(["Sex","Pclass"])["Survived"].sum().to_frame()  #to convert into dataframe

               Survived
Sex    Pclass
female 1             90
       2             70
       3             72
male   1             45
       2             17
       3             47

In [117]:
df.groupby(["Sex","Pclass"])["Survived"].sum().to_frame().reset_index()

      Sex  Pclass  Survived
0  female       1        90
1  female       2        70
2  female       3        72
3    male       1        45
4    male       2        17
5    male       3        47

In [118]:
df.groupby(["Sex","Pclass"])["Survived"].sum().unstack()

Pclass   1   2   3
Sex
female  90  70  72
male    45  17  47

In [120]:
a=df.groupby("Pclass").sum(numeric_only = True)

In [121]:
a

        Survived      Age  SibSp  Parch        Fare
Pclass
1            135  7073.42     89     77  18106.1292
2             87  5168.83     74     70   3801.8417
3            119  8924.92    302    193   6714.6951

In [122]:
a.T

Pclass             1          2          3
Survived    135.0000    87.0000   119.0000
Age        7073.4200  5168.8300  8924.9200
SibSp        89.0000    74.0000   302.0000
Parch        77.0000    70.0000   193.0000
Fare      18106.1292  3801.8417  6714.6951

In [123]:
a.transpose()

Pclass             1          2          3
Survived    135.0000    87.0000   119.0000
Age        7073.4200  5168.8300  8924.9200
SibSp        89.0000    74.0000   302.0000
Parch        77.0000    70.0000   193.0000
Fare      18106.1292  3801.8417  6714.6951

In [125]:
df.head().T

,0,1,2,3,4
Name,"Braund, Mr. Owen Harris","Heikkinen, Miss. Laina","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James"
Survived,0,1,1,0,0
Pclass,3,3,1,3,3
Sex,male,female,female,male,male
Age,22.0,26.0,35.0,35.0,NaN
SibSp,1,0,1,0,0
Parch,0,0,0,0,0
Ticket,A/5 21171,STON/O2. 3101282,113803,373450,330877
Fare,7.25,7.925,53.1,8.05,8.4583
Cabin,NaN,NaN,C123,NaN,NaN
Embarked,S,S,S,S,Q